table fact_churn
	lineageTag: fc-001

	measure TotalCustomers = COUNT(fact_churn[customer_id])
		formatString: #,##0
		displayFolder: KPIs
		lineageTag: fc-m-001

	measure ChurnedCustomers = CALCULATE(COUNTROWS(fact_churn), fact_churn[churn_flag] = 1)
		formatString: #,##0
		displayFolder: KPIs
		lineageTag: fc-m-002

	measure ChurnRate = DIVIDE(SUM(fact_churn[churn_flag]), COUNT(fact_churn[customer_id]), 0)
		formatString: 0.00%
		displayFolder: KPIs
		lineageTag: fc-m-003

	measure AvgMonthlyCharges = AVERAGE(fact_churn[monthly_charges])
		formatString: $#,##0.00
		displayFolder: KPIs
		lineageTag: fc-m-004

	measure AvgTenure = AVERAGE(fact_churn[tenure])
		formatString: 0.0
		displayFolder: KPIs
		lineageTag: fc-m-005

	measure CustomerLifetimeValue = AVERAGE(fact_churn[monthly_charges]) * AVERAGE(fact_churn[tenure])
		formatString: $#,##0.00
		displayFolder: Advanced
		lineageTag: fc-m-006

	measure RetentionRate = 1 - [ChurnRate]
		formatString: 0.00%
		displayFolder: Advanced
		lineageTag: fc-m-007

	measure RevenueAtRisk = [ChurnedCustomers] * [AvgMonthlyCharges] * [AvgTenure]
		formatString: $#,##0.00
		displayFolder: Advanced
		lineageTag: fc-m-008

	measure ChurnImpactPct = DIVIDE([RevenueAtRisk], [CustomerLifetimeValue] * [TotalCustomers], 0)
		formatString: 0.00%
		displayFolder: Advanced
		lineageTag: fc-m-009

	measure TotalRevenue = SUM(fact_churn[total_charges])
		formatString: $#,##0.00
		displayFolder: KPIs
		lineageTag: fc-m-010

	column churn_id
		dataType: int64
		isHidden
		lineageTag: fc-002
		summarizeBy: sum
		sourceColumn: churn_id

	column customer_id
		dataType: string
		lineageTag: fc-003
		summarizeBy: none
		sourceColumn: customer_id

	column tenure
		dataType: int64
		lineageTag: fc-004
		summarizeBy: sum
		sourceColumn: tenure

	column monthly_charges
		dataType: double
		formatString: $#,##0.00
		lineageTag: fc-005
		summarizeBy: sum
		sourceColumn: monthly_charges

	column total_charges
		dataType: double
		formatString: $#,##0.00
		lineageTag: fc-006
		summarizeBy: sum
		sourceColumn: total_charges

	column contract_type
		dataType: string
		lineageTag: fc-007
		summarizeBy: none
		sourceColumn: contract_type

	column payment_method
		dataType: string
		lineageTag: fc-008
		summarizeBy: none
		sourceColumn: payment_method

	column internet_service
		dataType: string
		lineageTag: fc-009
		summarizeBy: none
		sourceColumn: internet_service

	column churn_label
		dataType: string
		lineageTag: fc-010
		summarizeBy: none
		sourceColumn: churn_label

	column churn_flag
		dataType: int64
		lineageTag: fc-011
		summarizeBy: sum
		sourceColumn: churn_flag

	column tenure_group
		dataType: string
		lineageTag: fc-012
		summarizeBy: none
		sourceColumn: tenure_group
		sortByColumn: tenure_group_sort

	column paperless_billing
		dataType: string
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: paperless_billing

		annotation SummarizationSetBy = Automatic

	column multiple_lines
		dataType: string
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678901
		summarizeBy: none
		sourceColumn: multiple_lines

		annotation SummarizationSetBy = Automatic

	column online_security
		dataType: string
		lineageTag: c3d4e5f6-a7b8-9012-cdef-123456789012
		summarizeBy: none
		sourceColumn: online_security

		annotation SummarizationSetBy = Automatic

	column online_backup
		dataType: string
		lineageTag: d4e5f6a7-b8c9-0123-defa-234567890123
		summarizeBy: none
		sourceColumn: online_backup

		annotation SummarizationSetBy = Automatic

	column device_protection
		dataType: string
		lineageTag: e5f6a7b8-c9d0-1234-efab-345678901234
		summarizeBy: none
		sourceColumn: device_protection

		annotation SummarizationSetBy = Automatic

	column tech_support
		dataType: string
		lineageTag: f6a7b8c9-d0e1-2345-fabc-456789012345
		summarizeBy: none
		sourceColumn: tech_support

		annotation SummarizationSetBy = Automatic

	column streaming_tv
		dataType: string
		lineageTag: a7b8c9d0-e1f2-3456-abcd-567890123456
		summarizeBy: none
		sourceColumn: streaming_tv

		annotation SummarizationSetBy = Automatic

	column streaming_movies
		dataType: string
		lineageTag: b8c9d0e1-f2a3-4567-bcde-678901234567
		summarizeBy: none
		sourceColumn: streaming_movies

		annotation SummarizationSetBy = Automatic

	column churn_probability
		dataType: double
		lineageTag: c9d0e1f2-a3b4-5678-cdef-789012345678
		summarizeBy: sum
		sourceColumn: churn_probability

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d0e1f2a3-b4c5-6789-defa-890123456789
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column avg_daily_charge
		dataType: double
		lineageTag: e1f2a3b4-c5d6-7890-efab-901234567890
		summarizeBy: sum
		sourceColumn: avg_daily_charge

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tenure_group_sort
		dataType: int64
		isHidden
		lineageTag: fc-013
		summarizeBy: sum
		sourceColumn: tenure_group_sort

	partition fact_churn = m
		mode: import
		source =
				let
					Source = PostgreSQL.Database("localhost:5433", "finsight"),
					fact_churn = Source{[Schema="public",Item="fact_churn"]}[Data],
					#"Added Sort" = Table.AddColumn(fact_churn, "tenure_group_sort", each if [tenure_group] = "0-6 months" then 1 else if [tenure_group] = "6-12 months" then 2 else if [tenure_group] = "12-24 months" then 3 else if [tenure_group] = "24-48 months" then 4 else if [tenure_group] = "48+ months" then 5 else 99, Int64.Type)
				in
					#"Added Sort"

